export const ROUTES = {
  error: "/error",
  notFound: "*",
  login: "/login",
  registrarse: "/registrarse",
  recuperar: "/recuperar",
  home: "/",
  acercaDe: "/acerca-de",
  comoEmpezar: "/como-empezar",
  proyectos: "/proyectos",
  proyectoDetalle: "/proyectos/:nombre",
  noticias: "/noticias",
  noticiaDetalle: "/noticias/:titulo",
  contacto: "/contacto",
  faq: "/preguntas-frecuentes",
  terminos: "/terminos-y-condiciones",
  admin: "/admin",
  adminResenias: "/admin/resenias",
  adminNoticias: "/admin/noticias",
  adminNoticiasNueva: "/admin/noticias/nueva-noticia",
  adminNoticiasEditar: "/admin/noticias/editar/:id",
  adminFaq: "/admin/preguntas-frecuentes",
  adminProyectos: "/admin/proyectos",
  adminProyectosNuevo: "/admin/proyectos/nuevo-proyecto",
  adminProyectosEditar: "/admin/proyectos/editar/:nombre",
} as const;
