import type { Proyecto } from "../../components/Proyectos/organisms/GridProyectos";

export const proyectosMock: Proyecto[] = [
  {
    id: 1,
    titulo: "Proyecto 1",
    resumen:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor.",
    categorias: ["Educación", "Ciencia"],
    imagen1: "/images/imagen1.png",
    imagen2: "/images/imagen2.png",
    imagen3: "/images/imagen3.jpg",
  },
  {
    id: 2,
    titulo: "Proyecto 2",
    resumen: "Exploración interactiva con RA para conceptos de física.",
    categorias: ["Ciencia"],
    imagen1: "/images/imagen2.png",
    imagen2: "/images/imagen3.jpg",
    imagen3: "/images/imagen1.png",
  },
  {
    id: 3,
    titulo: "Proyecto 3",
    resumen: "Visor UA3D para eventos académicos inmersivos.",
    categorias: ["Eventos", "Tecnología", "Educación"],
    imagen1: "/images/imagen3.jpg",
    imagen2: "/images/imagen1.png",
    imagen3: "/images/imagen2.png",
  },
  {
    id: 4,
    titulo: "Proyecto 4",
    resumen: "Laboratorio IoT con sensores simulados en RA.",
    categorias: ["Tecnología", "Ciencia"],
    imagen1: "/images/imagen1.png",
    imagen2: "/images/imagen3.jpg",
    imagen3: "/images/imagen2.png",
  },
  {
    id: 5,
    titulo: "Proyecto 5",
    resumen: "Matemáticas básicas con estaciones interactivas.",
    categorias: ["Educación"],
    imagen1: "/images/imagen2.png",
    imagen2: "/images/imagen1.png",
    imagen3: "/images/imagen3.jpg",
  },
  {
    id: 6,
    titulo: "Proyecto 6",
    resumen: "Entorno colaborativo para aprendizaje de idiomas.",
    categorias: ["Educación", "Eventos", "Tecnología"],
    imagen1: "/images/imagen3.jpg",
    imagen2: "/images/imagen2.png",
    imagen3: "/images/imagen1.png",
  },
  {
    id: 7,
    titulo: "Proyecto 7",
    resumen: "Biología amazónica: biodiversidad en RA.",
    categorias: ["Ciencia", "Educación"],
    imagen1: "/images/imagen1.png",
    imagen2: "/images/imagen2.png",
    imagen3: "/images/imagen3.jpg",
  },
  {
    id: 8,
    titulo: "Proyecto 8",
    resumen: "Visualización de datos y analítica en RA.",
    categorias: ["Tecnología"],
    imagen1: "/images/imagen2.png",
    imagen2: "/images/imagen3.jpg",
    imagen3: "/images/imagen1.png",
  },
  {
    id: 9,
    titulo: "Proyecto 9",
    resumen:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor.",
    categorias: ["Educación", "Eventos"],
    imagen1: "/images/imagen1.png",
    imagen2: "/images/imagen2.png",
    imagen3: "/images/imagen3.jpg",
  },
  {
    id: 10,
    titulo: "Proyecto 10",
    resumen: "Exploración interactiva con RA para conceptos de física.",
    categorias: ["Ciencia", "Tecnología", "Eventos"],
    imagen1: "/images/imagen2.png",
    imagen2: "/images/imagen3.jpg",
    imagen3: "/images/imagen1.png",
  },
  {
    id: 11,
    titulo: "Proyecto 11",
    resumen: "Visor UA3D para eventos académicos inmersivos.",
    categorias: ["Eventos"],
    imagen1: "/images/imagen3.jpg",
    imagen2: "/images/imagen1.png",
    imagen3: "/images/imagen2.png",
  },
  {
    id: 12,
    titulo: "Proyecto 12",
    resumen: "Laboratorio IoT con sensores simulados en RA.",
    categorias: ["Tecnología", "Educación"],
    imagen1: "/images/imagen1.png",
    imagen2: "/images/imagen3.jpg",
    imagen3: "/images/imagen2.png",
  },
  {
    id: 13,
    titulo: "Proyecto 13",
    resumen: "Matemáticas básicas con estaciones interactivas.",
    categorias: ["Educación", "Ciencia", "Eventos"],
    imagen1: "/images/imagen2.png",
    imagen2: "/images/imagen1.png",
    imagen3: "/images/imagen3.jpg",
  },
  {
    id: 14,
    titulo: "Proyecto 14",
    resumen: "Entorno colaborativo para aprendizaje de idiomas.",
    categorias: ["Educación", "Tecnología"],
    imagen1: "/images/imagen3.jpg",
    imagen2: "/images/imagen2.png",
    imagen3: "/images/imagen1.png",
  },
  {
    id: 15,
    titulo: "Proyecto 15",
    resumen: "Biología amazónica: biodiversidad en RA.",
    categorias: ["Ciencia", "Eventos"],
    imagen1: "/images/imagen1.png",
    imagen2: "/images/imagen2.png",
    imagen3: "/images/imagen3.jpg",
  },
  {
    id: 16,
    titulo: "Proyecto 16",
    resumen: "Visualización de datos y analítica en RA.",
    categorias: ["Tecnología", "Ciencia", "Educación"],
    imagen1: "/images/imagen2.png",
    imagen2: "/images/imagen3.jpg",
    imagen3: "/images/imagen1.png",
  },
];
